wandb_version: 1

n_embd:
  desc: null
  value: 288
n_head:
  desc: null
  value: 12
n_layer:
  desc: null
  value: 12
block_size:
  desc: null
  value: 512
vocab_size:
  desc: null
  value: 50304
dropout:
  desc: null
  value: 0.0
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722350118.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.12.3
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
